config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_notes
  resources :inwoner_notes
  resources :inwoners
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "inwoners#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inwoner.rb
class Inwoner < ApplicationRecord
  has_many :inwoner_notes
  has_many :vehicles
end

app/models/inwoner_note.rb
class InwonerNote < ApplicationRecord
  belongs_to :user
  belongs_to :inwoner
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  validates :username, uniqueness: true
  has_many :inwoner_notes
  has_many :vehicle_notes
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :inwoner
  has_many :vehicle_notes
end

app/models/vehicle_note.rb
class VehicleNote < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inwoner_notes_controller.rb
class InwonerNotesController < ApplicationController
  before_action :set_inwoner_note, only: %i[ show edit update destroy ]

  # GET /inwoner_notes or /inwoner_notes.json
  def index
    @inwoner_notes = InwonerNote.all
  end

  # GET /inwoner_notes/1 or /inwoner_notes/1.json
  def show
  end

  # GET /inwoner_notes/new
  def new
    @inwoner_note = InwonerNote.new
  end

  # GET /inwoner_notes/1/edit
  def edit
  end

  # POST /inwoner_notes or /inwoner_notes.json
  def create
    @inwoner_note = InwonerNote.new(inwoner_note_params)

    respond_to do |format|
      if @inwoner_note.save
        format.html { redirect_to inwoner_note_url(@inwoner_note), notice: "Inwoner note was successfully created." }
        format.json { render :show, status: :created, location: @inwoner_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inwoner_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inwoner_notes/1 or /inwoner_notes/1.json
  def update
    respond_to do |format|
      if @inwoner_note.update(inwoner_note_params)
        format.html { redirect_to inwoner_note_url(@inwoner_note), notice: "Inwoner note was successfully updated." }
        format.json { render :show, status: :ok, location: @inwoner_note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inwoner_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inwoner_notes/1 or /inwoner_notes/1.json
  def destroy
    @inwoner_note.destroy

    respond_to do |format|
      format.html { redirect_to inwoner_notes_url, notice: "Inwoner note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inwoner_note
      @inwoner_note = InwonerNote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inwoner_note_params
      params.require(:inwoner_note).permit(:body, :user_id, :inwoner_id)
    end
end

app/controllers/inwoners_controller.rb
class InwonersController < ApplicationController
  before_action :set_inwoner, only: %i[ show edit update destroy ]

  # GET /inwoners or /inwoners.json
  def index
    @inwoners = Inwoner.all
  end

  # GET /inwoners/1 or /inwoners/1.json
  def show
  end

  # GET /inwoners/new
  def new
    @inwoner = Inwoner.new
  end

  # GET /inwoners/1/edit
  def edit
  end

  # POST /inwoners or /inwoners.json
  def create
    @inwoner = Inwoner.new(inwoner_params)

    respond_to do |format|
      if @inwoner.save
        format.html { redirect_to inwoner_url(@inwoner), notice: "Inwoner was successfully created." }
        format.json { render :show, status: :created, location: @inwoner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inwoner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inwoners/1 or /inwoners/1.json
  def update
    respond_to do |format|
      if @inwoner.update(inwoner_params)
        format.html { redirect_to inwoner_url(@inwoner), notice: "Inwoner was successfully updated." }
        format.json { render :show, status: :ok, location: @inwoner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inwoner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inwoners/1 or /inwoners/1.json
  def destroy
    @inwoner.destroy

    respond_to do |format|
      format.html { redirect_to inwoners_url, notice: "Inwoner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inwoner
      @inwoner = Inwoner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inwoner_params
      params.require(:inwoner).permit(:identifier, :firstname, :lastname, :dateofbirth, :sex)
    end
end

app/controllers/vehicle_notes_controller.rb
class VehicleNotesController < ApplicationController
  before_action :set_vehicle_note, only: %i[ show edit update destroy ]

  # GET /vehicle_notes or /vehicle_notes.json
  def index
    @vehicle_notes = VehicleNote.all
  end

  # GET /vehicle_notes/1 or /vehicle_notes/1.json
  def show
  end

  # GET /vehicle_notes/new
  def new
    @vehicle_note = VehicleNote.new
  end

  # GET /vehicle_notes/1/edit
  def edit
  end

  # POST /vehicle_notes or /vehicle_notes.json
  def create
    @vehicle_note = VehicleNote.new(vehicle_note_params)

    respond_to do |format|
      if @vehicle_note.save
        format.html { redirect_to vehicle_note_url(@vehicle_note), notice: "Vehicle note was successfully created." }
        format.json { render :show, status: :created, location: @vehicle_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_notes/1 or /vehicle_notes/1.json
  def update
    respond_to do |format|
      if @vehicle_note.update(vehicle_note_params)
        format.html { redirect_to vehicle_note_url(@vehicle_note), notice: "Vehicle note was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle_note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_notes/1 or /vehicle_notes/1.json
  def destroy
    @vehicle_note.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_notes_url, notice: "Vehicle note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_note
      @vehicle_note = VehicleNote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_note_params
      params.require(:vehicle_note).permit(:body, :vehicle_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inwoner_notes_helper.rb
module InwonerNotesHelper
end

app/helpers/inwoners_helper.rb
module InwonersHelper
end

app/helpers/vehicle_notes_helper.rb
module VehicleNotesHelper
end

app/views/inwoner_notes/_form.html.erb
<%= form_with(model: inwoner_note) do |form| %>
  <% if inwoner_note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inwoner_note.errors.count, "error") %> prohibited this inwoner_note from being saved:</h2>

      <ul>
        <% inwoner_note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :inwoner_id, style: "display: block" %>
    <%= form.text_field :inwoner_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inwoner_notes/_inwoner_note.html.erb
<div id="<%= dom_id inwoner_note %>">
  <p>
    <strong>Body:</strong>
    <%= inwoner_note.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= inwoner_note.user_id %>
  </p>

  <p>
    <strong>Inwoner:</strong>
    <%= inwoner_note.inwoner_id %>
  </p>

</div>

app/views/inwoner_notes/edit.html.erb
<h1>Editing inwoner note</h1>

<%= render "form", inwoner_note: @inwoner_note %>

<br>

<div>
  <%= link_to "Show this inwoner note", @inwoner_note %> |
  <%= link_to "Back to inwoner notes", inwoner_notes_path %>
</div>

app/views/inwoner_notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inwoner notes</h1>

<div id="inwoner_notes">
  <% @inwoner_notes.each do |inwoner_note| %>
    <%= render inwoner_note %>
    <p>
      <%= link_to "Show this inwoner note", inwoner_note %>
    </p>
  <% end %>
</div>

<%= link_to "New inwoner note", new_inwoner_note_path %>

app/views/inwoner_notes/new.html.erb
<h1>New inwoner note</h1>

<%= render "form", inwoner_note: @inwoner_note %>

<br>

<div>
  <%= link_to "Back to inwoner notes", inwoner_notes_path %>
</div>

app/views/inwoner_notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inwoner_note %>

<div>
  <%= link_to "Edit this inwoner note", edit_inwoner_note_path(@inwoner_note) %> |
  <%= link_to "Back to inwoner notes", inwoner_notes_path %>

  <%= button_to "Destroy this inwoner note", @inwoner_note, method: :delete %>
</div>

app/views/inwoners/_form.html.erb
<%= form_with(model: inwoner) do |form| %>
  <% if inwoner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inwoner.errors.count, "error") %> prohibited this inwoner from being saved:</h2>

      <ul>
        <% inwoner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :identifier, style: "display: block" %>
    <%= form.text_field :identifier %>
  </div>

  <div>
    <%= form.label :firstname, style: "display: block" %>
    <%= form.text_field :firstname %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :dateofbirth, style: "display: block" %>
    <%= form.text_field :dateofbirth %>
  </div>

  <div>
    <%= form.label :sex, style: "display: block" %>
    <%= form.text_field :sex %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inwoners/_inwoner.html.erb
<div id="<%= dom_id inwoner %>">
  <p>
    <strong>Identifier:</strong>
    <%= inwoner.identifier %>
  </p>

  <p>
    <strong>Firstname:</strong>
    <%= inwoner.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= inwoner.lastname %>
  </p>

  <p>
    <strong>Dateofbirth:</strong>
    <%= inwoner.dateofbirth %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= inwoner.sex %>
  </p>

</div>

app/views/inwoners/edit.html.erb
<h1>Editing inwoner</h1>

<%= render "form", inwoner: @inwoner %>

<br>

<div>
  <%= link_to "Show this inwoner", @inwoner %> |
  <%= link_to "Back to inwoners", inwoners_path %>
</div>

app/views/inwoners/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inwoners</h1>

<div id="inwoners">
  <% @inwoners.each do |inwoner| %>
    <%= render inwoner %>
    <p>
      <%= link_to "Show this inwoner", inwoner %>
    </p>
  <% end %>
</div>

<%= link_to "New inwoner", new_inwoner_path %>

app/views/inwoners/new.html.erb
<h1>New inwoner</h1>

<%= render "form", inwoner: @inwoner %>

<br>

<div>
  <%= link_to "Back to inwoners", inwoners_path %>
</div>

app/views/inwoners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inwoner %>

<div>
  <%= link_to "Edit this inwoner", edit_inwoner_path(@inwoner) %> |
  <%= link_to "Back to inwoners", inwoners_path %>

  <%= button_to "Destroy this inwoner", @inwoner, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiveM Meos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <%= yield %>
    <footer>
      <div class="content has-text-centered">
        <p>MEOS voor FiveM | Created by <a href="https://github.com/NotAtec">Atec</a></p>
      </div>
    </footer>

  </body>
</html>

app/views/vehicle_notes/_form.html.erb
<%= form_with(model: vehicle_note) do |form| %>
  <% if vehicle_note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle_note.errors.count, "error") %> prohibited this vehicle_note from being saved:</h2>

      <ul>
        <% vehicle_note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :vehicle_id, style: "display: block" %>
    <%= form.text_field :vehicle_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_notes/_vehicle_note.html.erb
<div id="<%= dom_id vehicle_note %>">
  <p>
    <strong>Body:</strong>
    <%= vehicle_note.body %>
  </p>

  <p>
    <strong>Vehicle:</strong>
    <%= vehicle_note.vehicle_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= vehicle_note.user_id %>
  </p>

</div>

app/views/vehicle_notes/edit.html.erb
<h1>Editing vehicle note</h1>

<%= render "form", vehicle_note: @vehicle_note %>

<br>

<div>
  <%= link_to "Show this vehicle note", @vehicle_note %> |
  <%= link_to "Back to vehicle notes", vehicle_notes_path %>
</div>

app/views/vehicle_notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vehicle notes</h1>

<div id="vehicle_notes">
  <% @vehicle_notes.each do |vehicle_note| %>
    <%= render vehicle_note %>
    <p>
      <%= link_to "Show this vehicle note", vehicle_note %>
    </p>
  <% end %>
</div>

<%= link_to "New vehicle note", new_vehicle_note_path %>

app/views/vehicle_notes/new.html.erb
<h1>New vehicle note</h1>

<%= render "form", vehicle_note: @vehicle_note %>

<br>

<div>
  <%= link_to "Back to vehicle notes", vehicle_notes_path %>
</div>

app/views/vehicle_notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vehicle_note %>

<div>
  <%= link_to "Edit this vehicle note", edit_vehicle_note_path(@vehicle_note) %> |
  <%= link_to "Back to vehicle notes", vehicle_notes_path %>

  <%= button_to "Destroy this vehicle note", @vehicle_note, method: :delete %>
</div>